// [WARNING] This file is generated by running `$ qore codegen` on your root project, please do not edit

/// <reference types="@feedloop/qore-client" />
import { QoreSchema } from "@feedloop/qore-client";

declare module "@feedloop/qore-client" {
  type CategoryTableRow = {
    id: string;
    name: string;
    description: string;
    activity: { nodes: ActivityTableRow[] };
  };

  type ClickShareTableRow = {
    id: string;
    name: string;
    program: ProgramTableRow;
  };

  type DonationTableRow = {
    id: string;
    name: string;
    description: string;
    email: string;
    phone: string;
    nominal: number;
    campaign: CampaignTableRow;
    image: string;
    dateTransfer: Date;
    recentDonation: string;
    valid: boolean;
    state: string;
    finalState: string;
  };

  type MemberTableRow = {
    id: string;
    email: string;
    role: { id: string; displayField: string };
    secret: string;
  };

  type PicTableRow = {
    id: string;
    name: string;
    description: string;
    phone: string;
    email: string;
    campaign2: { nodes: Campaign2TableRow[] };
    divisi: string;
  };

  type ProgramTableRow = {
    id: string;
    name: string;
    description: string;
    dateStart: Date;
    dateEnd: Date;
    state: string;
    category: CategoryTableRow;
    donation: { nodes: DonationTableRow[] };
    dateTransfer: Date;
    dateActivity: Date;
    pic: PicTableRow;
    stateProgram: StateProgramTableRow;
    state2: State2TableRow;
    penerima: string;
    phone: string;
    alamat: string;
    organisasi: string;
    target: number;
    active: string;
    clickDonasi: { nodes: ClickDonasiTableRow[] };
    image: string;
    achievement: number;
    totalDonatur: number;
    totalShare: number;
    listDonatur: string;
    achivement: number;
  };

  type RekeningTableRow = {
    id: string;
    name: string;
    description: string;
    nomor: string;
  };

  type ShareViewRow = {
    read: {
      id: string;
      name: string;
      program: ProgramTableRow;
    };
    write: {
      name: string;
      program: string[];
    };
    params: {};
    actions: {};
    forms: {};
  };

  type AllRekeningViewRow = {
    read: {
      id: string;
      name: string;
      description: string;
      nomor: string;
    };
    write: {
      name: string;
      description: string;
      nomor: string;
    };
    params: {};
    actions: {};
    forms: {};
  };

  type RecentDonationViewRow = {
    read: {
      id: string;
      name: string;
      description: string;
      email: string;
      phone: string;
      nominal: number;
      dateTransfer: Date;
      campaign: CampaignTableRow;
    };
    write: {
      name: string;
      description: string;
      email: string;
      phone: string;
      nominal: number;
      dateTransfer: Date;
      campaign: string[];
    };
    params: {
      finalState?: number;
    };
    actions: {};
    forms: {};
  };

  type AllMemberViewRow = {
    read: {
      id: string;
      email: string;
      role: { id: string; displayField: string };
      secret: string;
    };
    write: {
      email: string;
      secret: string;
    };
    params: {};
    actions: {};
    forms: {};
  };

  type AllCategoryViewRow = {
    read: {
      id: string;
      name: string;
      description: string;
    };
    write: {
      name: string;
      description: string;
    };
    params: {};
    actions: {};
    forms: {};
  };

  type AllDonationViewRow = {
    read: {
      id: string;
      name: string;
      description: string;
      email: string;
      phone: string;
      nominal: number;
      campaign: CampaignTableRow;
      image: string;
      dateTransfer: Date;
      valid: boolean;
      state: string;
      finalState: string;
    };
    write: {
      name: string;
      description: string;
      email: string;
      phone: string;
      nominal: number;
      campaign: string[];
      image: string;
      dateTransfer: Date;
      valid: boolean;
      state: string;
    };
    params: {
      "$by.dateTransfer"?: "desc";
    };
    actions: {};
    forms: {};
  };

  type AllPicViewRow = {
    read: {
      id: string;
      name: string;
      description: string;
      phone: string;
      email: string;
      divisi: string;
    };
    write: {
      name: string;
      description: string;
      phone: string;
      email: string;
      divisi: string;
    };
    params: {
      name?: string;
    };
    actions: {};
    forms: {};
  };

  type TopProgramViewRow = {
    read: {
      id: string;
      name: string;
      description: string;
      dateStart: Date;
      dateEnd: Date;
      category: CategoryTableRow;
      target: number;
      active: string;
      achievement: number;
      totalDonatur: number;
      image: string;
    };
    write: {
      name: string;
      description: string;
      dateStart: Date;
      dateEnd: Date;
      category: string[];
      target: number;
      image: string;
    };
    params: {
      active?: string;
    };
    actions: {};
    forms: {};
  };

  type ActivityViewRow = {
    read: {
      id: string;
      name: string;
      description: string;
      dateStart: Date;
      dateEnd: Date;
      category: CategoryTableRow;
      pic: PicTableRow;
      penerima: string;
      alamat: string;
      totalShare: number;
      listDonatur: string;
      achivement: number;
      target: number;
      image: string;
      achievement: number;
      state: string;
      totalDonatur: number;
    };
    write: {
      name: string;
      description: string;
      dateStart: Date;
      dateEnd: Date;
      category: string[];
      pic: string[];
      penerima: string;
      alamat: string;
      target: number;
      image: string;
      state: string;
    };
    params: {};
    actions: {};
    forms: {};
  };

  type AllProgramViewRow = {
    read: {
      id: string;
      name: string;
      description: string;
      dateStart: Date;
      dateEnd: Date;
      state: string;
      category: CategoryTableRow;
      dateTransfer: Date;
      dateActivity: Date;
      pic: PicTableRow;
      penerima: string;
      phone: string;
      alamat: string;
      organisasi: string;
      target: number;
      image: string;
      achievement: number;
    };
    write: {
      name: string;
      description: string;
      dateStart: Date;
      dateEnd: Date;
      state: string;
      category: string[];
      dateTransfer: Date;
      dateActivity: Date;
      pic: string[];
      penerima: string;
      phone: string;
      alamat: string;
      organisasi: string;
      target: number;
      image: string;
    };
    params: {};
    actions: {};
    forms: {};
  };

  type ProjectSchema = {
    share: ShareViewRow;
    allRekening: AllRekeningViewRow;
    recentDonation: RecentDonationViewRow;
    allMember: AllMemberViewRow;
    allCategory: AllCategoryViewRow;
    allDonation: AllDonationViewRow;
    allPic: AllPicViewRow;
    topProgram: TopProgramViewRow;
    activity: ActivityViewRow;
    allProgram: AllProgramViewRow;
  };
}
